# Generated by Django 4.2.5 on 2024-06-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippng_address',
            new_name='shipping_address',
        ),
    ]
