# Generated by Django 4.2.5 on 2024-06-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
