# Generated by Django 4.2.5 on 2024-05-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_product',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
